package utlpfor

import (
	"encoding/binary"
	"math/bits"
	"slices"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// encodeValuesSeed converts uint32 values to a byte slice for fuzz seeding.
func encodeValuesSeed(values []uint32) []byte {
	buf := make([]byte, len(values)*4)
	for i, v := range values {
		binary.LittleEndian.PutUint32(buf[i*4:], v)
	}
	return buf
}

// decodeValuesSeed converts a fuzz-generated byte slice back to uint32 values.
// Limits to blockSize values to stay within valid block sizes.
func decodeValuesSeed(data []byte) []uint32 {
	n := min(len(data)/4, blockSize)
	values := make([]uint32, n)
	for i := range values {
		values[i] = binary.LittleEndian.Uint32(data[i*4:])
	}
	return values
}

func FuzzPackUnpackUint32RoundTrip(f *testing.F) {
	f.Add(encodeValuesSeed([]uint32{0, 1, 2, 3}))
	f.Add(encodeValuesSeed([]uint32{0xFFFFFFFF}))
	f.Add(encodeValuesSeed(make([]uint32, 128)))
	f.Add(encodeValuesSeed([]uint32{0, 255, 256, 65535, 65536, 0xFFFFFF, 0x1000000, 0xFFFFFFFF}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		original := slices.Clone(values)
		packed, err := PackUint32(0, values, nil, nil)
		require.NoError(t, err)

		unpacked, consumed, err := UnpackUint32(packed, nil, make([]uint32, blockSize))
		require.NoError(t, err)
		require.Equal(t, len(packed), consumed)
		require.Equal(t, original, unpacked)
	})
}

func FuzzPackDeltaUint32RoundTrip(f *testing.F) {
	f.Add(encodeValuesSeed([]uint32{10, 20, 30, 40, 50}))
	f.Add(encodeValuesSeed([]uint32{100, 50, 200, 10}))
	f.Add(encodeValuesSeed([]uint32{0, 0, 0, 0}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		original := slices.Clone(values)
		packed, err := PackUint32(Delta, values, nil, nil)
		require.NoError(t, err)

		unpacked, _, err := UnpackUint32(packed, nil, make([]uint32, blockSize))
		require.NoError(t, err)
		require.Equal(t, original, unpacked)
	})
}

func FuzzGetUint32MatchesUnpack(f *testing.F) {
	f.Add(encodeValuesSeed([]uint32{1, 2, 3, 4, 5}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		packed, err := PackUint32(0, values, nil, nil)
		require.NoError(t, err)

		unpacked, _, err := UnpackUint32(packed, nil, make([]uint32, blockSize))
		require.NoError(t, err)

		scratch := make([]uint32, ScratchLen)
		for pos := range unpacked {
			got, err := GetUint32(pos, packed, scratch)
			require.NoError(t, err)
			require.Equal(t, unpacked[pos], got, "pos=%d", pos)
		}
	})
}

func FuzzBlockLengthNeverPanics(f *testing.F) {
	f.Add([]byte{})
	f.Add([]byte{0x00, 0x00, 0x00, 0x00})
	f.Add([]byte{0xFF, 0xFF, 0xFF, 0xFF})

	f.Fuzz(func(t *testing.T, data []byte) {
		_, _ = BlockLength(data)
	})
}

func FuzzCorruptDeltaOverflow(f *testing.F) {
	f.Add(encodeValuesSeed([]uint32{0xFFFFFFFF, 0xFFFFFFFF, 1}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) < 2 || len(values) > blockSize {
			return
		}

		packed, err := PackUint32(Delta, values, nil, nil)
		if err != nil {
			return
		}

		_, _, err = UnpackUint32(packed, nil, make([]uint32, blockSize))
		assert.NoError(t, err)
	})
}

func FuzzDeltaWithExceptions(f *testing.F) {
	f.Add(encodeValuesSeed([]uint32{100, 200, 0xFFFFFF, 400, 500}))
	f.Add(encodeValuesSeed([]uint32{0, 0, 0x10000, 0, 0, 0, 0, 0x1000000}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		original := slices.Clone(values)
		packed, err := PackUint32(Delta, values, nil, nil)
		if err != nil {
			return
		}

		unpacked, _, err := UnpackUint32(packed, nil, make([]uint32, blockSize))
		require.NoError(t, err)
		require.Equal(t, original, unpacked,
			"delta+exceptions round-trip must preserve values")
	})
}

func FuzzMaxBlockLength32Invariant(f *testing.F) {
	f.Add(encodeValuesSeed(make([]uint32, 128)), byte(0))
	f.Add(encodeValuesSeed([]uint32{0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF}), byte(0))
	f.Add(encodeValuesSeed(make([]uint32, 128)), byte(NoPatch))
	f.Add(encodeValuesSeed(make([]uint32, 128)), byte(NoPatch|NoFOR))
	f.Add(encodeValuesSeed(make([]uint32, 128)), byte(NoFOR))

	f.Fuzz(func(t *testing.T, data []byte, rawFlag byte) {
		values := decodeValuesSeed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		flag := Flag(rawFlag) & (Delta | NoFOR | NoPatch | Special | Append)
		flag &^= Append

		packed, err := PackUint32(flag, slices.Clone(values), nil, nil)
		if err != nil {
			return
		}

		maxSize := MaxBlockLength32(flag)
		assert.LessOrEqual(t, len(packed), maxSize,
			"packed %d bytes exceeds MaxBlockLength32(%d)=%d", len(packed), flag, maxSize)
	})
}

func FuzzCompressionRatio(f *testing.F) {
	f.Add(encodeValuesSeed(make([]uint32, 128)))
	f.Add(encodeValuesSeed([]uint32{1, 2, 3, 4, 5, 6, 7, 8}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValuesSeed(data)
		if len(values) < 16 {
			return
		}

		maxBW := 0
		for _, v := range values {
			bw := bits.Len32(v)
			if bw > maxBW {
				maxBW = bw
			}
		}

		packed, err := PackUint32(0, values, nil, nil)
		if err != nil {
			return
		}

		theoreticalPacked := headerBytes + utlPayloadBytes(maxBW)
		rawSize := len(values) * 4
		if maxBW < 32 && theoreticalPacked < rawSize {
			assert.LessOrEqual(t, len(packed), rawSize,
				"blocks with sub-32-bit values should compress (bw=%d, count=%d)", maxBW, len(values))
		}
	})
}

// encodeValues64Seed converts uint64 values to a byte slice for fuzz seeding.
func encodeValues64Seed(values []uint64) []byte {
	buf := make([]byte, len(values)*8)
	for i, v := range values {
		binary.LittleEndian.PutUint64(buf[i*8:], v)
	}
	return buf
}

// decodeValues64Seed converts a fuzz-generated byte slice to uint64 values.
func decodeValues64Seed(data []byte) []uint64 {
	n := min(len(data)/8, blockSize)
	values := make([]uint64, n)
	for i := range values {
		values[i] = binary.LittleEndian.Uint64(data[i*8:])
	}
	return values
}

func FuzzPackUnpackUint64RoundTrip(f *testing.F) {
	f.Add(encodeValues64Seed([]uint64{0, 1, 2, 3}))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFFF}))
	f.Add(encodeValues64Seed([]uint64{0x100000000}))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFFFFFFFFFFF}))
	f.Add(encodeValues64Seed(make([]uint64, 128)))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFC0, 0xFFFFFFC1, 0xFFFFFFC2, 0x100000000}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValues64Seed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		original := slices.Clone(values)
		scratch := make([]uint32, ScratchLen64)
		packed, err := PackUint64(0, values, nil, scratch)
		require.NoError(t, err)

		dst := make([]uint64, blockSize)
		unpacked, consumed, err := UnpackUint64(dst, scratch, packed)
		require.NoError(t, err)
		require.Equal(t, len(packed), consumed)
		require.Equal(t, original, unpacked)
	})
}

func FuzzPackDeltaUint64RoundTrip(f *testing.F) {
	f.Add(encodeValues64Seed([]uint64{10, 20, 30, 40, 50}))
	f.Add(encodeValues64Seed([]uint64{0x100000000, 0x100000001, 0x100000002}))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFFE, 0xFFFFFFFF, 0x100000000, 0x100000001}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValues64Seed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		original := slices.Clone(values)
		scratch := make([]uint32, ScratchLen64)
		packed, err := PackUint64(Delta, values, nil, scratch)
		require.NoError(t, err)

		dst := make([]uint64, blockSize)
		unpacked, _, err := UnpackUint64(dst, scratch, packed)
		require.NoError(t, err)
		require.Equal(t, original, unpacked)
	})
}

func FuzzGetUint64MatchesUnpack(f *testing.F) {
	f.Add(encodeValues64Seed([]uint64{1, 2, 3, 4, 5}))
	f.Add(encodeValues64Seed([]uint64{0x100000000, 0x200000000}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValues64Seed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		scratch := make([]uint32, ScratchLen64)
		packed, err := PackUint64(0, slices.Clone(values), nil, scratch)
		require.NoError(t, err)

		dst := make([]uint64, blockSize)
		unpacked, _, err := UnpackUint64(dst, scratch, packed)
		require.NoError(t, err)

		for pos := range unpacked {
			got, err := GetUint64(pos, packed, scratch)
			require.NoError(t, err)
			require.Equal(t, unpacked[pos], got, "pos=%d", pos)
		}
	})
}

func FuzzMaxBlockLength64Invariant(f *testing.F) {
	f.Add(encodeValues64Seed(make([]uint64, 128)), byte(0))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFFFFFFFFFFF}), byte(0))
	f.Add(encodeValues64Seed(make([]uint64, 128)), byte(NoPatch))
	f.Add(encodeValues64Seed(make([]uint64, 128)), byte(NoPatch|NoFOR))
	f.Add(encodeValues64Seed(make([]uint64, 128)), byte(NoFOR))

	f.Fuzz(func(t *testing.T, data []byte, rawFlag byte) {
		values := decodeValues64Seed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		flag := Flag(rawFlag) & (Delta | NoFOR | NoPatch | Special | Append)
		flag &^= Append

		scratch := make([]uint32, ScratchLen64)
		packed, err := PackUint64(flag, slices.Clone(values), nil, scratch)
		if err != nil {
			return
		}

		maxSize := MaxBlockLength64(flag)
		assert.LessOrEqual(t, len(packed), maxSize,
			"packed %d bytes exceeds MaxBlockLength64(%d)=%d", len(packed), flag, maxSize)
	})
}

func FuzzBlockLengthUint64MatchesConsumed(f *testing.F) {
	f.Add(encodeValues64Seed([]uint64{0, 1, 2, 3}))
	f.Add(encodeValues64Seed([]uint64{0x100000000, 0x100000001}))
	f.Add(encodeValues64Seed([]uint64{0xFFFFFFC0, 0xFFFFFFC1, 0x100000000}))

	f.Fuzz(func(t *testing.T, data []byte) {
		values := decodeValues64Seed(data)
		if len(values) == 0 || len(values) > blockSize {
			return
		}

		scratch := make([]uint32, ScratchLen64)
		packed, err := PackUint64(0, slices.Clone(values), nil, scratch)
		if err != nil {
			return
		}

		bl, err := BlockLength(packed)
		require.NoError(t, err)

		dst := make([]uint64, blockSize)
		_, consumed, err := UnpackUint64(dst, scratch, packed)
		require.NoError(t, err)
		assert.Equal(t, consumed, bl, "BlockLength != consumed")
	})
}
