package utlpfor

import "encoding/binary"

// encodeValuesSeed converts uint32 values to a byte slice for fuzz seeding.
func encodeValuesSeed(values []uint32) []byte {
	buf := make([]byte, len(values)*4)
	for i, v := range values {
		binary.LittleEndian.PutUint32(buf[i*4:], v)
	}
	return buf
}

// decodeValuesSeed converts a fuzz-generated byte slice back to uint32 values.
// Limits to blockSize values to stay within valid block sizes.
func decodeValuesSeed(data []byte) []uint32 {
	n := len(data) / 4
	if n > blockSize {
		n = blockSize
	}
	values := make([]uint32, n)
	for i := range values {
		values[i] = binary.LittleEndian.Uint32(data[i*4:])
	}
	return values
}
